#!/usr/bin/python
from cmdgen import parse
import sys

if len(sys.argv) > 1 and sys.argv[1] == '-n':
    for option in parse(sys.stdin.read()):
        print option
else:
    while True:
        try:
            s = raw_input('# ')
        except (EOFError,KeyboardInterrupt):
            break
        if not s:
            continue
        for option in parse(s):
            print option